#!/usr/bin/env bash
#
# generate-quality-docs.sh — regenerate the coverage-derived sections of the
# quality docs from the SINGLE machine-readable source of truth
# (.github/go-test-report.json).
#
# It rewrites the region between these markers in each quality.md:
#   <!-- BEGIN:GENERATED-COVERAGE --> ... <!-- END:GENERATED-COVERAGE -->
# leaving all prose outside the markers untouched. The JSON is produced/committed
# by the coverage workflow (soulteary/go-test-report-action), so docs never carry
# hand-typed coverage numbers that can drift from the measured run.
#
# Usage:
#   scripts/generate-quality-docs.sh          # rewrite docs in place
#
# CI enforces `generate-quality-docs.sh && git diff --exit-code` so a stale doc
# fails the build.
#
# Exit codes:
#   0  docs regenerated
#   2  missing dependency / input

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JSON="$REPO_ROOT/.github/go-test-report.json"

if [ ! -f "$JSON" ]; then
  echo "error: quality source not found: $JSON" >&2
  exit 2
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required to render quality docs" >&2
  exit 2
fi

python3 - "$JSON" "$REPO_ROOT" <<'PY'
import json, sys, io, os, re

json_path, repo_root = sys.argv[1], sys.argv[2]
with open(json_path, encoding="utf-8") as fh:
    data = json.load(fh)

cov = data["coverage"]
total = cov["percentage"]
threshold = cov["threshold"]
pkgs = {p["name"]: p for p in data["packages"]}
env = data.get("environment", {})

BEGIN = "<!-- BEGIN:GENERATED-COVERAGE -->"
END = "<!-- END:GENERATED-COVERAGE -->"

def env_val(key, default="unknown"):
    v = env.get(key)
    return v if v else default

def env_block(lang):
    commit = env_val("commit")
    generated_at = env_val("generated_at")
    go_version = env_val("go_version")
    os_arch = f"{env_val('os')}/{env_val('arch')}"
    if lang == "en":
        return (
            "## Environment of record\n\n"
            f"- Commit: `{commit}`\n"
            f"- Generated (UTC): `{generated_at}`\n"
            f"- Go version: `{go_version}`\n"
            f"- OS / arch: `{os_arch}`\n\n"
            "These values come from the `environment` block of "
            "`.github/go-test-report.json`, the single machine-readable source "
            "of truth, so they cannot drift from the recorded run.\n\n"
        )
    return (
        "## 记录环境\n\n"
        f"- 提交：`{commit}`\n"
        f"- 生成时间（UTC）：`{generated_at}`\n"
        f"- Go 版本：`{go_version}`\n"
        f"- 操作系统 / 架构：`{os_arch}`\n\n"
        "这些值取自 `.github/go-test-report.json` 的 `environment` 字段"
        "（唯一的机器可读来源），因此不会与实际运行漂移。\n\n"
    )

def pkg_cov(name):
    p = pkgs.get(name)
    return f"{p['coverage']:.1f}%" if p else "n/a"

def block(lang):
    if lang == "en":
        rows = "\n".join(
            f"| `{n}` | `{pkg_cov(n)}` |"
            for n in ["pkg/license", "pkg/fingerprint", "internal/issuer", "cmd/license-tool"]
        )
        return (
            f"{BEGIN}\n"
            "<!-- Generated from .github/go-test-report.json by "
            "scripts/generate-quality-docs.sh. Do not edit by hand. -->\n\n"
            f"{env_block('en')}"
            "## Total coverage\n\n"
            f"- **Total:** `{total:.2f}%` of statements "
            f"({cov['covered_statements']}/{cov['total_statements']})\n"
            f"- Coverage gate (CI): `{threshold}%` (floor of the measured total; "
            "set so the same commit cannot fail its own gate)\n\n"
            "The Coverage badge in the root README is generated by CI from the "
            "same run.\n\n"
            "## Per-package coverage\n\n"
            "| Package | Coverage |\n| ------- | -------- |\n"
            f"{rows}\n"
            "| `examples/client` | `0.0%` (illustrative example, no tests) |\n\n"
            f"{END}"
        )
    else:
        rows = "\n".join(
            f"| `{n}` | `{pkg_cov(n)}` |"
            for n in ["pkg/license", "pkg/fingerprint", "internal/issuer", "cmd/license-tool"]
        )
        return (
            f"{BEGIN}\n"
            "<!-- 由 scripts/generate-quality-docs.sh 从 .github/go-test-report.json "
            "生成，请勿手工编辑。 -->\n\n"
            f"{env_block('zh')}"
            "## 总覆盖率\n\n"
            f"- **总计：** `{total:.2f}%` 语句覆盖率"
            f"（{cov['covered_statements']}/{cov['total_statements']}）\n"
            f"- 覆盖率门禁（CI）：`{threshold}%`（实测总覆盖率向下取整；确保同一提交不会失败于自身门禁）\n\n"
            "根 README 的 Coverage 徽章由 CI 基于同一次运行生成。\n\n"
            "## 分包覆盖率\n\n"
            "| 包 | 覆盖率 |\n| -- | ------ |\n"
            f"{rows}\n"
            "| `examples/client` | `0.0%`（示例代码，无测试） |\n\n"
            f"{END}"
        )

targets = {
    os.path.join(repo_root, "docs", "enUS", "quality.md"): "en",
    os.path.join(repo_root, "docs", "zhCN", "quality.md"): "zh",
}

pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
for path, lang in targets.items():
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if BEGIN not in text or END not in text:
        sys.stderr.write(f"error: markers not found in {path}\n")
        sys.exit(2)
    text = pat.sub(block(lang), text)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"regenerated coverage block in {os.path.relpath(path, repo_root)}")
PY

echo "quality docs regenerated from $(basename "$JSON")"
